import './globals.css'
import type { Metadata } from 'next'
import Providers from "@/components/context/providers";
import React from "react";
import Main from "@/components/main/main";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body>
        <Providers>
          <Main>
            {children}
          </Main>
        </Providers>
      </body>
    </html>
  )
}
